# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/index.html'
    weight: 10
  - name: News
    url: '#news'
    weight: 20
  - name: Research
    url: '#research'
    weight: 30
  - name: CV
    url: '#cv'
    weight: 40
  - name: Publications
    url: '#publications'
    weight: 50
  - name: Hobbies
    url: '#hobbies'
    weight: 60
  